# -*- coding: utf-8 -*-
"""zboson_mass_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nai0Uu3Xu7T1c48otwMLoGckyLoLSgTA

# Step 0. Importing useful packages

 Most python scripts start with 'import' statements like this that make useful packages available. Examples are 'uproot' which reads in our data files and allows them to be read, 'numpy' is a powerful and popular package for fast manipulation of arrays and 'scipy.stats' is useful for statistical analysis - we'll use it to generate and fit functions to our data.
"""

!pip install awkward vector uproot
!pip install awkward-pandas

import numpy as np
import matplotlib.pyplot as plt
import awkward as ak
import uproot as uproot
import vector
import pandas as pd
from scipy import stats
from scipy.stats import cauchy
from scipy.stats import norm

"""# Step 1. Access the data file and convert into a 'pandas dataframe'.

 - Here the file is converted into the very poweful 'pandas dataframe' format which is used a lot in modern
     statistical analysis. You can think of the dataframe as a super-charged spreadsheet. Each row represents
     a proton-proton collision event, and every column represents a piece of information ('observable') we have
     recorded from that event.

 - We are going to work with 7 observables: the components of the muon's four-vector, the charge of the muon and two     extra variables related to how isolated the muon is from other particles. As we will have two muons produced in       each event, that makes 14 observables per event.


The first thing we want to do is read our data file. It contains ~500k proton collision events from the ATLAS Open Data pre-selected so that each event contains two muon candidates with transverse mometum greater than 20000 MeV.
"""

eventsData = uproot.open("data_Skim_mumu.root")["mini"] #this command tells uproot where to find the file

df = eventsData.arrays(["muon_E", "muon_pt", "muon_phi", "muon_eta", "muon_charge", "muon_etcone20", "muon_ptcone30"], library="pd")
print("File has been successfully opened!")

"""We said dataframes are like spreadsheets and we can see that structure directly by simply typing the name of the variable representing the dataframe ("df") into the prompt.
We'll see the familiar row/column structure with our twelve observables and lots of events!
"""

df.head()

"""You will see each event has values of the variables for "muon[0]" and "muon[1]". These refer to the muon
with the larger and smaller pt values respectively.

The next thing we want to do is apply some more criteria to our data so that it is dominated as much as possible by the Z->mumu process, while still retaining as many events as possible.
"""

# Exporting the unfiltered data to csv
# Split the lists in the DataFrame columns into separate columns for each muon
df_split = pd.DataFrame()
for col in df.columns:
    df_split[col + '_0'] = df[col].apply(lambda x: x[0])
    df_split[col + '_1'] = df[col].apply(lambda x: x[1])

# Now export the modified dataframe to csv
df_split.to_csv("raw_data.csv")
df_split.info()

"""# Step 2. Apply event selections"""

#cut0: we require the charges of the muons to be opposite (by requiring the sum to be 0)
cuts0 = df[ df['muon_charge'].apply(lambda x: x[0] + x[1] == 0)]

#cut1: we require the transervse momentum of each muon to be above 20000 MeV'
cuts1 = cuts0[(cuts0["muon_pt"]).apply(lambda x: x[0] > 39990 and x[0] < 56000) & (cuts0["muon_pt"]).apply(lambda x: x[1] > 39990 and x[1] < 56000)]

#cut2: we require the absolute pseudorapidity of each muon to be below 2.4'

cuts2 = cuts1[(cuts1["muon_eta"]).apply(lambda x: np.abs(x[0]) < 2.2  and np.abs(x[0]) > 0.2) & (cuts1["muon_eta"]).apply(lambda x: np.abs(x[1]) < 2.2 and np.abs(x[1]) > 0.2)  ]

#we copy our finally selected dataframe to a new variable 'finalData' for convenience
finalData =  cuts2

#let's check how many events we have selected after all our criteria have been applied
print("Number of selected events = " + str(len(finalData.index)))

# Reseting the index of the filtered data
finalData = finalData.reset_index(drop=True)
# have a look at our finally selected dataframe
finalData.head()

# Exporting the filtered data to csv
# Split the lists in the DataFrame columns into separate columns for each muon
df_split = pd.DataFrame()
for col in finalData.columns:
    df_split[col + '_0'] = finalData[col].apply(lambda x: x[0])
    df_split[col + '_1'] = finalData[col].apply(lambda x: x[1])

# Now export the modified dataframe to csv
df_split.to_csv("filtered_data.csv")
df_split.info()

""" # Step 3. 'Reconstruct' the Z boson by adding the four-vectors of each muon."""

#first we make arrays of four-vectors for the muons. we make separate arrays for leading and sub-leading muons
pt0 = finalData['muon_pt'].apply(lambda x: x[0]).to_numpy()
eta0 = finalData['muon_eta'].apply(lambda x: x[0]).to_numpy()
phi0 = finalData['muon_phi'].apply(lambda x: x[0]).to_numpy()
E0 = finalData['muon_E'].apply(lambda x: x[0]).to_numpy()

pt1 = finalData['muon_pt'].apply(lambda x: x[1]).to_numpy()
eta1 = finalData['muon_eta'].apply(lambda x: x[1]).to_numpy()
phi1 = finalData['muon_phi'].apply(lambda x: x[1]).to_numpy()
E1 = finalData['muon_E'].apply(lambda x: x[1]).to_numpy()

lvArray0 = vector.array(
    {
        "pt": pt0,
        "phi": phi0,
        "eta": eta0,
        "E": E0,
    }
)

lvArray1 = vector.array(
    {
        "pt": pt1,
        "phi": phi1,
        "eta": eta1,
        "E": E1,
    }
)

# the vector package conveniently allows us to simply add the arrays to get an array of four-vectors representing the dimuon system in each event
lvArray = lvArray0 + lvArray1

"""# Step 4.  Make histogram plots of the kinematic information of the muon pairs."""

#################################################################

# let's make some simple histograms of the kineamtic information associated with the muons.

# plot the mu[0] pt histogram.
plt.figure()
plt.title(r"Transverse Momentum ($p_T$) Distribution of Muon 1")
plt.xlabel(r"$p_T$ [MeV/$c$]")
plt.ylabel("Frequency")
plt.grid(axis='y', alpha=0.3)
plt.hist(lvArray0.pt, bins=35, edgecolor= "black",range=[30000,60000], linewidth = 0.7, alpha=0.6, color='g')

#plot the mu[0] pseudorapdity histogram.
plt.figure()
plt.title(r"Pseudorapidity ($\eta$) Distribution of Muon 1")
plt.xlabel(r"$\eta$")
plt.ylabel("Frequency")
plt.axvline(0, color='red', linestyle='--', alpha=0.5, label='Central (η=0)')
plt.grid(axis='y', alpha=0.3)
plt.hist(lvArray0.eta, bins=35, edgecolor= "black", range=[-3.0,3.0],linewidth = 0.7, alpha=0.6, color='g')

#################################################################

# plot the mu[1] pt histogram.
plt.figure()
plt.title(r"Transverse Momentum ($p_T$) Distribution of Muon 2")
plt.xlabel(r"$p_T$ [MeV/$c$]")
plt.ylabel("Frequency")
plt.grid(axis='y', alpha=0.3)
plt.hist(lvArray1.pt, bins=35, edgecolor= "black",range=[30000,60000], linewidth = 0.7, alpha=0.6, color='r')

#plot the mu[1] pseudorapdity histogram.
plt.figure()
plt.title(r"Pseudorapidity ($\eta$) Distribution of Muon 2")
plt.xlabel(r"$\eta$")
plt.ylabel("Frequency")
plt.axvline(0, color='red', linestyle='--', alpha=0.5, label='Central (η=0)')
plt.grid(axis='y', alpha=0.3)
plt.hist(lvArray1.eta, bins=35, edgecolor= "black", range=[-3.0,3.0],linewidth = 0.7, alpha=0.6, color='r')

"""# Step 5. Make histogram plots of the kinematic information of the muons.
- now that we have reconstructed four-vectors of the dimuon system and know how to make histogram plots,let's make a histogram plot of the dimuon mass distribution and see if the Cauchy distribution can be seen and if the peak is somehwhere around 90 GeV

- we will compare this histogram to a cauchy pdf. However, pdfs are always normalised to an area of 1 while our data represents hundreds of thousands of events, so the data histogram will surely have an integral much larger than 1. Therefore we must first calculate this integral use it to scale our pdf to allow a fair visual comparison between the data histogram and the predicted Cauchy distribution.
"""

#we set up a few parmaters for our histogram, min and max of the x-axis (mass)
minMass = 71000
maxMass = 110000

#the number of bins
nBins = 250

# creating the histogram as two arrays (bin edges & counts in the bins) numpy
countsData, edges = np.histogram(lvArray.mass, bins=nBins, range=(minMass, maxMass))

# get the width of each bin
bin_width = edges[1] - edges[0]
# sum over number in each bin and multiply by bin width, which can be factored out.
# This gives us the integral
integral = bin_width * sum(countsData[0:nBins])

# we can make an array of the centre of each bin directly from the edges array this will be useful in plotting our pdf
centres = (edges[1:] + edges[:-1]) / 2

#fit a Cauchy distributions to the dimuon mass data
mu, std = cauchy.fit(lvArray.mass)
print("mu = " + str(mu))   # best fit values
print("std = " + str(std))  # best fit values

"""So we are almost ready to compare our data histogram with the predicted Cauchy distribution but we know the Cauchy pdf has two free parameters: the mean (mu) and standard deviation (sigma). what should we choose for these values for a first comparison? Why not the world-average values published by the Particle Data group below..."""

mZPDG  = 91187.6
sigmaZPDG = 2495.2

#let's make the comparison plot USING PDG VALUES
plt.figure()
p = (cauchy.pdf(centres, mZPDG, sigmaZPDG) * integral)
plt.title(r"$\mu^+\mu^-$ Pair Mass Distribution Fitted with Cauchy (PDG parameters)")
plt.plot(centres, p, 'k',label="Cauchy pdf (PDG values)", linewidth=1.5)
plt.hist(lvArray.mass, bins=nBins, range=[minMass, maxMass],label="ATLAS Data", alpha=0.6, color='g')
plt.legend(loc='upper right', frameon=True, fontsize=8,  framealpha=0.8)

plt.xlabel(r"$\mu^+\mu^-$ Mass [MeV]")
plt.ylabel("Frequency")

# Add PDG value annotation
plt.axvline(mZPDG, color='red', linestyle='--', alpha=0.5, linewidth=1.2)
plt.text(mZPDG+500, 0.8*plt.ylim()[1],
         rf"PDG $m_Z$ = {mZPDG/1:.2f} MeV",
         color='red', ha='left', fontsize=8)
plt.show()

################################################
# USING BEST FIT VALUES
print(f"\nFit results:")
print(f"- Best fit mass = {mu:.2f} MeV")
print(f"- Best fit width = {std:.2f} MeV")
mZPDG  = mu
sigmaZPDG = std
p = (cauchy.pdf(centres, mZPDG, sigmaZPDG) * integral)

"""The plot above shows a clear peak and a shape that looks very much like a Cauchy distrubtion. So we can be confident that our data conatains the decays of a heavy particle to pairs of muons. However the data does not perfectly agree with the predicted shape of Cauchy distributions with the PDG values for the mass and width of the Z boson.

# 6. Fitting the Cauchy model to the data
In the next part of this notebook we will try to assess if we can find values of the Z mass which result in a better 'agreement' between the data and Cauchy model. If we trust the Cauchy model completely, then this proceedure is a measurement of the Z mass. We'll define the agreement between our data and model with the chi-squared function. The function takes in arrays of event counts ('obs') and predictions ('preds') corresponding to the bins of the dimuon mass distribution. The function returns the squared difference between the event count and prediction divided by the variance on the prediction, summed over all bins, otherwise known as the chi-squared function.
"""

#chi-squared function
def calcChiSq(obs, preds):
    chiSq = 0.0
    ndf = len(obs)
    for bin in range(0, len(obs)):
        diff = preds[bin] - obs[bin]
        var = ( np.abs(preds[bin])) # pearson's chi2 (approximate the prediction's variance as poisson, i.e., take the prediction as the variance)
        if (var != 0):
            chiSq += (diff**2)/(var)
    return chiSq, ndf

"""To perform the fit we will:
- We'll now loop over a range of $m_{Z}$ values,
- Generate a cauchy distribution for each value and evaluate the $\chi^{2}$ between that distribution and the data histogram.
- find the $m_{Z}$ value that gives the smallest value of the $\chi^{2}$
- plot the $\Delta \chi^{2}$ vs the $m_{Z}$, and use the $\emph{critical values}$ of this curve to evaluate the uncertainties on $m_{Z}$
- compare the data histogram to the fitted Cauchy distribution
"""

#some arrays to hold the z mass and chi-squared values
mZAr = np.array([])
chi2Ar = np.array([])

#deciding the range of z mass values and how fine the steps in this range will be
minMz = 91285
maxMz = 91315
step = 1

#vairables to use in the loop to find value of z mass that gives smallest chi2
bestFitMz1D = 0.0
minChi2 = 10000000

for mZ in range(minMz, maxMz, step): #starting loop
    countsPDF = (cauchy.pdf(centres, mZ, sigmaZPDG) * integral) #building pdf for these values
    #countsPDF = (norm.pdf(centres, mZ, sigmaZPDG) * integral) #building pdf for these values
    chi2, ndf = calcChiSq(countsData, countsPDF) # call chi2 function to get chi2 for this particular pdf and data
    mZAr = np.append(mZAr, mZ) #adding values to arrays
    chi2Ar = np.append(chi2Ar, chi2)
    if(chi2 < minChi2): #keeping track of what is the smallest chi2 value we have found
        minChi2 = chi2
        bestFitMz1D = mZ

# as we will only be interested in the change in chi2 w.r.t. mZ,  we can rescale all the chi2
#values such that the minimum chi2 value is 0.
chi2Ar = chi2Ar - minChi2

#we expect the chi2 vs. mZ curve to be quadratic, so let's fit that fucntion to it.
z = np.polyfit(mZAr, chi2Ar, 2) #"2" for a second-order polynomial
p = np.poly1d(z)

#lets plot our chi2 values vs mz along with the fit
plt.figure()
fig, ax = plt.subplots()
ax.plot(mZAr, chi2Ar, 'r+', lw=5, alpha=0.6, label="Chi2 Evaluations")
ax.plot(mZAr, p(mZAr), 'b-', lw=2, alpha=0.6, label="Quadratic Fit")

# we can display the estimated uncertianty on mZ via critical values () of the delta chi-squared curve
y0 = 1.0
crit = (p - y0).roots # roots of the polynominal -1, i.e., the mz values where p = 1

#shading in the uncertainty band
px=np.arange(crit[1],crit[0],0.001)
ax.fill_between(px,p(px),alpha=0.5, color='g', label="Uncertainty")
ax.legend(loc='upper right', frameon=True, fontsize=8,  framealpha=0.8)
#setting reasonable axis ranges and titles
plt.title(r"A Plot of $\Delta\chi^2$ vs $M_{Z}$")
ax.set_xlim(minMz, maxMz)
ax.set_ylim(0.0, 3)
plt.xlabel(r"$M_{Z}$ [MeV]")
plt.ylabel(r"$\Delta\chi^2$")
plt.legend(loc='upper right', frameon=True, fontsize=8,  framealpha=0.8)

plt.show()

#print result and uncertainty
my1DResult = bestFitMz1D
my1DUncertainty = bestFitMz1D-crit[1]
print("best-fit = " + str(my1DResult) + " +/- " + str(my1DUncertainty))

# we now compare our data histogram with the cauchy distribution with the mean and standard deviation
# that minimise the chi-squared. This pdf should agree much better than the pdf with the PDG values.

plt.figure()
p = (cauchy.pdf(centres, my1DResult, sigmaZPDG))

pInt = bin_width * sum(p[0:nBins])
scale = integral/pInt
pScaled = (cauchy.pdf(centres, my1DResult, sigmaZPDG) *scale)

plt.plot(centres, pScaled, 'k', linewidth=1.5,label="Cauchy pdf (Best Fit Values)")

x = np.linspace(87000, 94000, 1000)
pScaledNorm = (norm.pdf(x, my1DResult, (sigmaZPDG*0.8) )*(0.6*scale))

#plt.plot(x, pScaledNorm, 'r', linewidth=2)
plt.title(r"$\mu^+\mu^-$ Pair Mass Distribution Fitted with Cauchy (Best-fit parameters)")
plt.hist(lvArray.mass, bins=nBins, range=[minMass, maxMass], alpha=0.6, color='g',label="ATLAS Data")

plt.legend(loc='upper right', frameon=True, fontsize=8,  framealpha=0.8)

plt.xlabel(r"$\mu^+\mu^-$ Mass [MeV]")
plt.ylabel("Frequency")
plt.axvline(my1DResult, color='red', linestyle='--', alpha=0.5, linewidth=1.2)
plt.text(my1DResult+500, 0.8*plt.ylim()[1],
         rf"$m_Z$ = {my1DResult:.2f} $+/-$ {my1DUncertainty:.2f} MeV",
         color='red', ha='left', fontsize=8)
plt.show()

#############################################################

"""# Try a double gaussian with curve_fit"""

from scipy.optimize import curve_fit

def gaussian(x, mean, amplitude, standard_deviation):
    return amplitude * np.exp( - ((x - mean) / standard_deviation) ** 2)

def doubleGaussian(x, mean1, amplitude1, standard_deviation1, mean2, amplitude2, standard_deviation2):
    gaus1 = amplitude1 * np.exp( - ((x - mean1) / standard_deviation1) ** 2)
    gaus2 = amplitude2 * np.exp( - ((x - mean2) / standard_deviation2) ** 2)
    return gaus1 + gaus2

#bestFitParams, covarianceMatrix = curve_fit(gaussian, centres, countsData, p0=[91000., 2000., 10000.])
bestFitParams, covarianceMatrix = curve_fit(doubleGaussian, centres, countsData, p0=[91000., 2000., 10000., 91000, 6000, 2000])

x_interval_for_fit = np.linspace(edges[0], edges[-1], 10000)
#plt.plot(x_interval_for_fit, gaussian(x_interval_for_fit, *bestFitParams), label='gaussian fit')
plt.title(r"$\mu^+\mu^-$ Pair Mass Distribution Data Fitted with A Double Gaussian(Best-fit parameters)")
plt.plot(x_interval_for_fit, doubleGaussian(x_interval_for_fit, *bestFitParams),'r-', linewidth=3, label='double gaussian fit')
plt.errorbar(centres, countsData, yerr=np.sqrt(countsData), label="Data", fmt='o', mfc='k', mec='k', mew=0.1, ecolor='k')
plt.legend()
plt.xlabel(r"$\mu^+\mu^-$ Mass [MeV]")
plt.ylabel("Data")

"""now we have a 'measurement' of mZ, let's make a plot comparing our measured value with that from
the PDG to assess how good our measurement is.
"""

mZPDGAr = np.array([mZPDG])
uncZPDG = 2.1 #MeV
uncZPDGAr = np.array([uncZPDG]) # https://pdg.lbl.gov/2018/listings/rpp2018-list-z-boson.pdf
yPDGAr = np.array([1.0])

mZ1D = np.array([my1DResult])
sigZ1D = np.array([my1DUncertainty])
y1D = np.array([2.0])

plt.figure()
ax = plt.gca()
ax.set_xlim(minMz-30, maxMz+30)#need to extend x axis range to include PDG value
ax.set_ylim(0.0, 3.0)
plt.title(r" Measured $m_Z$ Values for Comparison")

plt.errorbar(mZPDGAr, yPDGAr, xerr=uncZPDGAr, label="Particle Data Group", elinewidth=5,  fmt="*", mfc="blue", ms=8)
plt.errorbar(mZ1D, y1D, xerr=sigZ1D, fmt="*", label="ATLAS Open Data", elinewidth=5, ms=8, mfc='red')

plt.xlabel(r"$\mu^+\mu^-$ Mass [MeV]")
plt.yticks(y1D, " ")

ax.axes.yaxis.set_visible(False)
plt.legend()
plt.show()